apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: car-co2-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/your-username/Car-CO2-Volume-Prediction.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
