name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      - name: Run Unit Tests
        env:
          PYTHONPATH: .
        run: pytest tests/test_api.py
